apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: nico-ale-backend-pipeline-
spec:
  #serviceAccountName: build-bot
  pipelineRef:
    name: nico-ale-backend-pipeline
  params:
  - name: image-repo
    value: quay.io/lumander/nico-ale-backend
  - name: app-name
    value: nico-ale-backend
  workspaces:
    - name: pipeline-shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi